### ISSUE TITLE
Economy Doesn't like 0.12.1 :/

### ISSUE THREAD

**Issue by TheGalaxyLord** [onebone/EconomyS#167]
Please make economy compatible with Pocketmine 1.6 because when I make a shop it always crashes the server when I click on the shop sign

**Comment by patrickt1220** [comment]
PocketMine-MP Crash Dump Tue Sep 15 21:46:04 MDT 2015

Error: Call to undefined method pocketmine\item\ItemBlock::isPlaceable()
File: /EconomySell_v2.0.6.phar/src/onebone/economysell/EconomySell
Line: 206
Type: E_ERROR

THIS CRASH WAS CAUSED BY A PLUGIN
BAD PLUGIN: EconomySell v2.0.6

Code:
[197] 
[198] 			if($cnt >= $sell ["amount"]){
[199] 				$this->removeItem($player, new Item($sell["item"], $sell["meta"], $sell["amount"]));
[200] 				EconomyAPI::getInstance()->addMoney($player, $sell ["cost"], true, "EconomySell");
[201] 				$player->sendMessage($this->getMessage("sold-item", array($sell ["amount"], $sell ["item"].":".$sell ["meta"], $sell ["cost"] )));
[202] 			}else{
[203] 				$player->sendMessage($this->getMessage("no-item"));
[204] 			}
[205] 			$event->setCancelled(true);
[206] 			if($event->getItem()->isPlaceable()){
[207] 				$this->placeQueue [$player->getName()] = true;
[208] 			}
[209] 		}
[210] 	}
[211] 
[212] 	public function onPlace(BlockPlaceEvent $event){
[213] 		$username = $event->getPlayer()->getName();
[214] 		if(isset($this->placeQueue [$username])){
[215] 			$event->setCancelled(true);
[216] 			unset($this->placeQueue [$username]);

Backtrace:
#0 (): pocketmine\Server->crashDump(boolean)

PocketMine-MP version: 1.6dev #29 [Protocol 34; API 1.13.0]
Git commit: 0000000000000000000000000000000000000000
uname -a: Linux mc28.vgmc.us 2.6.32-431.el6.x86_64 #1 SMP Fri Nov 22 03:15:09 UTC 2013 x86_64
PHP Version: 5.6.2
Zend version: 2.6.0
OS : Linux, linux

Loaded plugins:
VIPSlots 0.0.4 by iJoshuaHD for API(s) 1.12.0
MineReset 2.1 by Falk for API(s) 1.0.0
iprotectorfix 1 by  for API(s) 1.0.0
InstantBreak 2.1.0 by kvetinac97 for API(s) 1.12.0
ASR 2.0.2 by iJoshuaHD for API(s) 1.12.0
CustomChat_2 1.0.0 by Array for API(s) 1.12.0
DevTools 1.10.0 by PocketMine Team for API(s) 1.3.1
TimeCommander 2 by LDX for API(s) 1.0.0, 1.1.0, 1.2.0, 1.3.0, 1.4.0
SimpleAuth 1.7.1 by PocketMine Team, shoghicp for API(s) 1.12.0
GrabBag 2.2.7 by aliuly for API(s) 1.10.0, 1.11.0, 1.12.0
BuyCraft 1.2.1 by Falkirks for API(s) 1.0.0
FastTransfer 1.0.2 by shoghicp for API(s) 1.12.0
NetherChests 1.1.1 by aliuly for API(s) 1.12.0
EconomyAPI 2.0.7 by onebone for API(s) 1.0.0, 1.1.0, 1.2.0, 1.2.1, 1.3.0, 1.3.1, 1.4.0, 1.4.1
iProtector 3.1a by LDX for API(s) 1.9.0
PurePerms 1.1.12 by 64FF00 for API(s) 1.13.0
Slapper 1.1.1 by jojoe77777 for API(s) 1.10.0
mcg76_SimplePortal 2.0.3 by minecraftgenius76 for API(s) 1.12.0
VoteReward 2.1 by LDX for API(s) 1.0.0, 1.1.0, 1.2.0, 1.3.0
MiniPE_Drugs 1.2 by Patrick for API(s) 1.12.0
AlwaysSpawn 2.2.2 by Philip Shilling for API(s) 1.12.0
SimpleAuthHelper 2.0.3 by aliuly for API(s) 1.12.0
EconomySell 2.0.6 by onebone for API(s) 1.12.0
SimpleWarp 2.0.3 by Falkirks for API(s) 1.12.0
EconomyShop 2.0.5 by onebone for API(s) 1.12.0
MyPlot 1 by Wies and Exxarion for API(s) 1.0.0
RankUp 0.3.0 by Falkirks for API(s) 1.4.0
ClearLagg 1.1.0 by LegendOfMCPE for API(s) 1.0.0

----------------------REPORT THE DATA BELOW THIS LINE-----------------------

===BEGIN CRASH DUMP===
eNrNWwlv20iy/isNJcDaD7ov2wo8gMdxdvLgJFrb2SwQBkaLbEmMeQ2btKwZzH/fr6qbl+yZOI4x
72WOkMXu6q/u6ib1eyvzQ9WaDcbj4ehgMpiO2y2VpnHamv3eyrYJHrXOrs8uLj5ctNqtUGktV0Q7
lUEgsljkkaeWfqQ8EapsHXsiid0blYUgOY6fqdBx3uL/Pwcgz2a+ngfSVXIRqL198Fv6ATHrnblx
FIfbSxUE17fDbr877SZrmfZ06vbiSC3wX0+ZMRpj6uPBJcBirdmwP/2j3UqCfOVHBLoxxI09RRIN
jg7wDITB0SEunIz+8Zd7L90oEz8di5fEXnx2WjKM8yhzWl/2f+fRR+VoJ3uZrX3d+SlVYXyrSLq9
l0kgtypti0hthKEQI/BhFbS+tEVBgJpkg1CttP8KSw37/dpSVoqT+dvZbKWyt5HOZORCeZ2fpOe9
g1621eIleDfWGa+RpblqC6euDKdllxnUJTIsOj9pFXnvjJH3rJhYtqA4LR0HXsfI1BYyTeV2777K
akis+F2nNXNa3ZLcVEINstgvtDAs4f2hAq1+Z+LoKZij2CIuWI8r1nw/Ke9fqlsVZcQyOyU9B4Hy
9kiJdua04TN2MNmFTA6bNPx732A+uO85CQ36V65yJT6XYoDNexli3hdxzIYzSx7ugC0cke8GxlfM
9cB49nBgVJfki8B3xTKP3MyPIxFHjG2PQ5Evzwi/MGIYsINCwS9zrdIIcIClJuecsZKkJVpGOShU
CrX4Gtrbe0jSgucXq5rBoxU/qBSfR99m/6qFTJCleNaafW696Iu9/VkjMV2q9JZ07qZSr1/nYbK3
iONAyWgfTtlaqUilMqB8gVEaysPqg+7UU7cAs8j9wEO6OUKySeMsdmOMHCFtysTncYNRt49xKz/D
bf+RfzAhlTeBv6A53QPmkJM0uD/3o/xOhO7wsHu7Ct1ursUQGXI07IxHg64Kpt27w+n1dCxeDMTl
u7l4k/rifXwrhkPRH80Gk1n/SHy8OhWI+ZEwQ8E9WSfgPQGjIe5+QxDhlvj2zcPrWBdrg8A3Ad+U
WVaThv79dn4ZxBlfW7wlqV3TXx9ZnZaVOcpEqskw/v/Gep3LX16T0ll7n0l9yP9EUBGFEUBxEmt5
KgFEmodnOl5mr+uEUHLSLzk6Tg1EEEuS7fLq5OLq4xyEjVpopATQ1lmW6FmvB2Ot80XXjcOe/5V5
rL1eyQISv4PfXCi4Xk3OilYTdNgdNIR8I4Obhnz9p4tHzpvSgo5TX9vKN/9wefXpw8X567qEUR4E
gO+Tqyo3i9Olf1cToUmvidEQ4pngNxZznESSHPToUSKY2pf9nCp5U5OgQa47HAzBrlyzxc2tyvxI
umgCnsvjKpa7sjzgblaSk8uLmgB018Td54j8uwLFf3c6P3McwHCcc0BX6feHTMGtR8JAwtNcZ3F4
upbZ9bAmaoPcbiTX/o6tPrdOdCJT1AKQ56m8o4QfxbfuOmt9eS4tNPk6ToXPcVz38a75Wt1eoX7U
c2BJaoo52JWzNeeyROEsrpQMGxYedQdPFa1Y33FqSL7PqhWyXskDwl5hv3Aah6GMyFUqiZv0ekZs
yHv++j/30mGbNGP/Htq/R/bv8dPNi6UcpwHre/LNpR8mgToB8pqQNWLTsAcw1V/aFTDX8Wrtu8mz
BXEFBh1NHdiT7VzjAg38M5WLn+WqJn5BaearYfegKbsM/DzYNuUs7VwY+kckNws4zgp4FnL1KLM+
JLoM1Fc4RhqDX69qEDu2v+llqVK9UOpMpb1Cdijm53x7msplvRcoSU23GO66BbUDfnqjn6slWORb
l9Z1nBqCR3j3Gwh1hfSql40gbpB3M/ROVXp2fy4YOk4dRvPuu727YNprcIEG3qtsrdLTtdKN5rVB
3kneu8Z8yM+fwasj5dLyf4tXN8SFVqoDh5pOasTdTmUn8u1hzaMyvImNKtOP7P24zPxPrn4WhuPY
QyNgcZyGFI/pmedFu1pvmCtiXRXALlt/WeeOfrCOVQsbvxg+wTHAqEPdXq8mBQSd56maqzSsh0FF
uxcDO2lgOn7zpt9vBsHo6cJeG36OUyKoXX5/baOZ1u0rLlTdA5kkjdRXUL4R81/jr7E6oD/369tT
855Z2XHCRzcnobs6mF6bcj2P08ycVlhJHni4G7ajplCUHriMrFTk5/pg+mw5jbE4Tp75QdGkGEjN
O7LR20fK/m+47oXayNSrnzlUxL/YjH9P8/kjwVqh+Z6OEy2YPz+7fp3mK908ZqjI9S16t9lZz2WW
+u7Ns5kO/KgOYQdBK3+PICfBRm71ZSI3UX2jW6PuNpA7OWW+9gM/EZf4K/Cj1bOJlDBfbdk6jmRI
miA9avN7b2vwiwp2ssjuo29E3lNaiPou5BHtxJqB/C3dxD3pq46CX8Tcayns65mmiqbf7im+raNa
tf+ORoFeR5SdQvF66bF7xU8yTe65AhO/4QQPbgq+38+b3Xsl5NKydxzNkJCXkiL9WniPkLFQyjpO
HrAjUXelnPwf2hF4KjsacI/JwNt5EDeOeA3hzw5GW598pQWiQ5zd3cmUBvzQvq7ZaduNOb3kq1nT
QEI4F9C+ma4uZHTzsW40S2gez492T6Ye9Mrx84lUbzwr8eC+NzlsV2J8hNlOAyXTc7mqH1VUtN2G
bkfMc4Wmx/uwpMb4uXbl5eL3q8rjm/Uarl4lzR/0+kWmEBIJt4DBr7O6SRoj52ZwSXB8MS/vxGkc
Lf2VoLftTupEL65yJS5VIgYTMRzMxpPZeCjevb6iF0QTGhDGmXf8rugJZ2J+JswbM3q4WQNyJ/B1
dtynexlFcR65VBD4RaZ01766VaGKMn0cRzSEC2zHnv7DEHZiEMSbzjLwV+vsOF4uq5Ey8kMZNGeH
8aIgrCB8GHvKsFnGKRYvaZbRGr2XG6flfXKb2Nmev1z6bh5k2+MBc+O3fdgKdbTKMrQF+pjIAWQI
QFJe7ZY+iDh+ffbm5OP5FVGNb3R+zVW6tewtKYXXF2vTdTeRWm/i1Dv+H/4D8fMs7mh5q+xEwp9u
odjQz44Hk9H0HQtv3lT6yfFw1D2i+DsY1+gJuufj0Wg6YlWE8s5aQR9P+xVsConjeerrOKImgB7Q
O76ylne3YUAuI+ipcNlbcuiEXhuT0wjoWFTHhJ13cziRuEJzqEShNCFTJbK1EohtjQuZCZdcIxML
JfzIDXJPebgQ95yVeF3GIWYuicEuTy2Xqi1iOqbQxFIs6FWP2MZ5ankJfylge3/p8wowewo/Q+sD
xu/VpmTX89RSwvBabOLoH5mgXZdMBRkihLAuHHIL+IJeCRi5N2sViTxZpdIDg64TkeINs5kTiRdX
azQ/nQAkoAhktMrlSgn62IRVZo2kfdwHMfj7v7FSaerpWrlWiuZEACiygYq6G//GT5Tny26crnp0
1ztH6F3Hy+u3lx+up6OjzvCa5kGNJaOZcJC2Vk6LFvq05iMe+liHvpQQ9OGOxk6B9JtRsxDIDHrj
x6xNRgocuFIZm9RTt76rxBqFLmAjh2Bs4q5aEl2GVqDrdZ55MUWs+QKDwJjsIdwg1sozsE4o+gWl
ESARtpkUt74U/6JowhCOqqLNnPEnETQR1XwjJHmpjoHGrmJMJS0jkWs4IVI1HIGlQ/WxHyiRnqoH
HcBaAFTF/ozjt+BDpZ3SiIC7wiMI6mIrrB9huI328mmlhhefsMmAMeFS0vNEqrTxPIIJX7sBHKlR
/yhPCvjbQpE+oHT1ay7506qVf4uxtzJAtt6zSyJF74O5WQ9ZRlEC6MCaq5VKZ3hKK7/PwwW0jXA6
0dvIvZL6Bh6f3iCAuvT8I4zA/lkISaPWKcp0DpfAaN2m8YEnbG6Ey7ahhhBa01RIWS0oXkQL8wiR
Q0OY9yW7DORBcKXxHfJ4pqACiMOuHpXQSKsGztslRSgNoUhsCz/7B31blvIsT1HNYC/cmSv2IAHs
LIakEZahY6WcMSeKVpNUOVb/GcQLKJZKtjBkwbmWclKoVnKxzQBIXBoofV7c12ReE+mQaeMzMFa2
oOJlc7YlmU5w6cNdkKb4ixbiskSOKFY05ocwOTvtKoYcMYUG6QzrrBikKQIz0Xc4VXBWzpBqpPf/
HD61P38BnoryD4HXWZzw+jZVlXgsNy0QUlRpkWUsGlqzgDToD8cGFbpOP+ZyRLGoaUGXE7JFV8bb
AEsh1XjkYzyig3hQJtI4jccREhgiFHqj7PBnajXqRO8UcIanWDfDHC64xAPRV0WySUe0wgdKIVTh
eHj3/mAS2zapUGGiXCqEmtVCWI2OzdxSAGhSJboSc9S3cur9BwFZqUdG6pVMF7B/x42DwHR0FGEP
apXdiaDYOcLOQeyGMsq55NZRoB3J4Qv77SIn7DiD9QaTV5fLIjeElZd1xQdT7/gOHrGO88ArgfjI
IJtIVNDJb0XCyCHgtN83MooXbzgS7uVG9hUzuxRqmcZhkWJprn3eqWelmk0hhDXdris84D+1edTf
ues8utFG3+fs9ZQQmUjIaJdB0ojio1AKzxQNiDaDOtQDUC9T8SJWhZltoBxNLc7XsZm2az7zQWEx
rc7BrGKHPYPMXIg6rqSjSJba+kKxED0oq/dfsnKiSGVki7J1g2sEphIu6KyTGxFJXS4KIPzJZiUO
QNOY2qcmGS1UWRM53byop6/iCQV+us2Id1t0BjVnptrHy3ayAgrSymRqskpVa7mFp0LnmXRnDWjm
gmgxdcUv2EhBvcfoheG4p/OPbcwFggXyz8b3srXJ2hzfJfsOs5+JA9sYVC2DZsXUhnbFiYd4Wstg
SR9lmy7GU/AzuxCWNP4XR/WALKtzjVetTzq7o+CjNkgGbRPYtPAnP0IXCbHgNopdm2r9x3k0LzqF
qmenJogm8YE7NexR0rG39Z4Mez+1yFcz23T8JAbUbNjKQl0lPy46Ss15bK2KTtOxpkAZqfpELXo6
k1kOh+mtXKNa+tRE1xYtdpKNfYMqmkjCDUnMjomHWvcicdngLpSYsYfZKR0zZSZCPFrZ/QQEMl97
Ay5cDk7KSUk2+CNz0o4sqy0PZWb30XCMsulevP9wdTYTnHXxr5tjcxVhc8WM+AiRTMfw7MolvNLE
Jw1rudhHIJNYWdmLuCQBCXlNRp4z7NsSQqnMVCZyI9oyE92WIxv1TXKRw0wvfEnhSgIupFa1xfYG
CJQHVmmLIR4MHnqgMre7z0GrVR0Fu8MVcaatld1/C4XEZNaj0m8syZvYandLiYB3QdQ9UTowryMM
b8un5keN/M1udMJf3NcKgLY9WwGC4BM32jIgN9PlTIz/fKpMQfUMdsOjWXXE4Gj44Gz2rkiZfeRC
GW4LtaRMxOc3lLHIDCVXc6pTS30m813KWxRd6u982i4r2n4lW3s0YGtR2dBwoljyq4ciLdo0tswD
HhZruGqHQtR3TSnhLVhK+3E4BtgWqvoa007IxIamD9/pdzHk1FRgSvl3jEEKLYzxTt4JuasX7IFc
rg+VPzRtwU56IT0/17Vp1g7SouMgNVOt39F4dCuUk+j4rJMnHnyxAoittpJmET6qq6qgAV5t7Ars
3fvgbf7bSJ/36L/yd/bGvnY+hz3TOxrGmonDJ3FL4iQPLDd7TaVph7ETcUx2oD0CbQ4JO+xHmjRJ
qgyRqzM6crHUgU0PdM42E6a5K0xK3/vnCZod0/EZh+TkYRoNywtcDmiWXZCYTuh2I2mhksg0GS58
eL4ZYo/4zB59ZpIRHSfQbw6EoZoaa53EeK/t5MvkRn7doQOeJqUsJw1qsk78aBlXbrCOyfa8ZLd2
3odGiPFFcbQNqc3nCNHQry6B0r7FPhbVYwYMX5NCrlaoPvZwoDx2oR6Rfnlx87A0Bg+x0w/hIX0Z
V2YT786GT5inM2OANOrY4lx1gEyNk9qB0SmdGfIhlgrihKpVG/eQgE7osqIVQ2eyRKesoGzUp4jq
PA2ypTUn6yAea0yEfatQ6yFyNJw6MwWuSHiWG1nIPC746x2lbDabh1QS+Cg3xipnd5LqrbmhhgX8
LYhZgYYfwdlppzwTn+mygyLT5q3zF+JosmDRhtRPW1mIYr9gNm3F2Tjvxh46vOXNLVcxzR0DiR2i
kfAB1Jb4GnRelQHwlaDjdQpdLknVajPx5vzkajZ8ddCeHN0N2qO7UXv4avDKQyU2WWuP3jq7lGGO
D/tiBf/W5m48oRJtz7qhRxK01W6pu0xFpB/+sOIUZan22xfyqNotqsOqNeMIarcSl4baG/1r4Gdq
ZH6i0zE/B/rN/GbHfDmycNHmrMvxdI4aeTKtCOYXlcVdngblzdIPMvqSAKztJ7LLLCmfrsLqeo1g
Nl9kYtBX3fjSNFyYo91yMFrEbZJVEmSSAHk1cS/n57wqXScuWrtq7hYC88+C7JWYdAkdSS469LZo
2J/0R7h8+RZmXI4ORkpOPG8yGR0eTAfj/lQe9odDOV4cytHBeDw4XAzHfSVe0qu/Naml/LFDEmv6
XUqhdLt3twMGJOiFWtqNJ6i83qGaLF2JxnWMZfvLgwP34PBwOplg6dHRcKRG/cXRwZHn8Xp6HcaV
CjXHmW5K6hvlY3AW36gIZSctKZ+UvEGCMIriF9tbye9Mii/EfvMTczfsjlt//PFfMo4J2w==
===END CRASH DUMP===

**Comment by onebone** [comment]
Check branch 'php7'
