### ISSUE TITLE
EconomyAPI rewrite

### ISSUE THREAD

**Issue by onebone** [onebone/EconomyS#230]
- Commands
 - [x] /givemoney
 - [x] /mymoney
 - [x] /mystatus
 - [x] /pay
 - [x] /seemoney
 - [x] /setlang
 - [x] /setmoney
 - [x] /takemoney
 - [x] /topmoney
- [x] Individual language preference system
- [x] Auto save scheduling

**Comment by dog194** [comment]
0.0.Why these command should rewrite?

**Comment by onebone** [comment]
@dog194 Current code of EconomyAPI is messy. So not only commands will be rewritten.

**Comment by SleepSpace9** [comment]
Hello, I downloaded the latest github source for EconomyS for testing php7 and tried to create a new Shop using a sign (first line "shop" and so on). But I was only able to create a new shop by the command "/shop create ...". I guess the "sign way" is still missing because of the core rewrite?
And if so, will it be implemented in the future again?

**Comment by onebone** [comment]
@SleepSpace9 Simply touch sign for the shop block!

**Comment by SleepSpace9** [comment]
Oh no, it's just too simple - sorry!  :see_no_evil: But great idea!  :thumbsup:
