### ISSUE TITLE
EconomyPShop Crash Error.

### ISSUE THREAD

**Issue by PainTR** [onebone/EconomyS#245]
How can i fix this? Please help me.
Error: Call to a member function getCloudForPlayer() on null
File: /EconomyPShop_v2.0.2.phar/src/onebone/economypshop/EconomyPShop
Line: 177
Type: E_ERROR

THIS CRASH WAS CAUSED BY A PLUGIN
BAD PLUGIN: EconomyPShop v2.0.2

Code:
[168] 				$now = microtime(true);
[169] 				if(!isset($this->tap[$player->getName()]) or $now - $this->tap[$player->getName()][1] >= 1.5  or $this->tap[$player->getName()][0] !== $loc){
[170] 					$this->tap[$player->getName()] = [$loc, $now];
[171] 					$player->sendMessage($this->getMessage("tap-again", [$shop["itemName"], $shop["price"], $shop["amount"]]));
[172] 					return;
[173] 				}else{
[174] 					unset($this->tap[$player->getName()]);
[175] 				}
[176] 
[177] 				if(($cloud = $this->itemcloud->getCloudForPlayer($shop["owner"])) instanceof \onebone\itemcloud\ItemCloud){
[178] 					if($shop["amount"] > $cloud->getCount($shop["item"], $shop["meta"])){
[179] 						$player->sendMessage($this->getMessage("no-stock"));
[180] 					}else{
[181] 						if($player->getInventory()->canAddItem(($item = new Item($shop["item"], $shop["meta"], $shop["amount"]))) === false){
[182] 							$player->sendMessage($this->getMessage("no-space"));
[183] 						}else{
[184] 							$api = \onebone\economyapi\EconomyAPI::getInstance();
[185] 							if($api->myMoney($player) > $shop["price"]){
[186] 								$player->getInventory()->addItem($item);
[187] 								$api->reduceMoney($player, $shop["price"], true, "EconomyPShop");

Backtrace:
#0 /src/pocketmine/Server(0): pocketmine\Server->crashDump(boolean)
#1 /src/pocketmine/plugin/MethodEventExecutor(41): onebone\economypshop\EconomyPShop->onBlockTouch(boolean)
#2 /src/pocketmine/plugin/RegisteredListener(101): pocketmine\plugin\MethodEventExecutor->execute(boolean)
#3 /src/pocketmine/plugin/PluginManager(678): pocketmine\plugin\RegisteredListener->callEvent(boolean)
#4 /src/pocketmine/level/Level(1879): pocketmine\plugin\PluginManager->callEvent(boolean)
#5 /src/pocketmine/Player(2116): pocketmine\level\Level->useItemOn(boolean)
#6 /src/pocketmine/network/RakLibInterface(145): pocketmine\Player->handleDataPacket(boolean)
#7 /src/raklib/server/ServerHandler(90): pocketmine\network\RakLibInterface->handleEncapsulated(boolean)
#8 /src/pocketmine/network/RakLibInterface(86): raklib\server\ServerHandler->handlePacket(boolean)
#9 /src/pocketmine/network/Network(165): pocketmine\network\RakLibInterface->process(boolean)
#10 /src/pocketmine/Server(2579): pocketmine\network\Network->processInterfaces(boolean)
#11 /src/pocketmine/Server(2332): pocketmine\Server->tick(boolean)
#12 /src/pocketmine/Server(2210): pocketmine\Server->tickProcessor(boolean)
#13 /src/pocketmine/Server(1811): pocketmine\Server->start(boolean)
#14 /src/pocketmine/PocketMine(469): pocketmine\Server->__construct(boolean)
#15 (1): (boolean)
#16 (0): {main}(boolean)

ImagicalMine version: 1.0dev #0 [Protocol 38; API 1.14.0]
Git commit: 0000000000000000000000000000000000000000
uname -a: Windows NT LENOVO-PC 6.3 build 9200 (Windows 8.1 Home Premium Edition) i586
PHP Version: 5.6.6
Zend version: 2.6.0
OS : WINNT, win

Loaded plugins:
DevBAN 1 by Ragnok123 for API(s) 1.13.1
DevTools 1.10.0 by PocketMine Team for API(s) 1.3.1
EconomyAPI 2.0.9 by onebone for API(s) 1.0.0, 1.1.0, 1.2.0, 1.2.1, 1.3.0, 1.3.1, 1.4.0, 1.4.1
EconomyLand 2.0.9 by onebone for API(s) 1.12.0
EconomyPShop 2.0.2 by onebone for API(s) 1.12.0
EssentialsPE 1.1.3 by LegendsOfMCPE Team for API(s) 1.12.0
WorldEditArt 1.0.0_beta_dev_#048 by PEMapModder for API(s) 1.0.0
WorldProtect 2.2.0 by aliuly for API(s) 1.10.0, 1.12.0
EasyKeep 1.0.0 by  for API(s) 1.12.0
ItemCloud 1.3 by onebone for API(s) 1.4.0
Marriage 1.0.4 by www.vk.com/topplugins for API(s) 1.11.0
RagnokBoost 1 by Ragnok123 for API(s) 1.12.0
MyPlot 1 by Wies and Exxarion for API(s) 1.0.0

**Comment by roberto12b** [comment]
I am having the same problem here

**Comment by SalmonGER** [comment]
I've also got this issue.

**Comment by onebone** [comment]
Did you install ItemCloud plugin?

**Comment by roberto12b** [comment]
ImagicalMine Crash Dump Mon Feb 8 15:05:26 UTC 2016

Error: Call to a member function getCloudForPlayer() on null
File: /EconomyPShop_v2.0.2.phar/src/onebone/economypshop/EconomyPShop
Line: 177
Type: E_ERROR

THIS CRASH WAS CAUSED BY A PLUGIN
BAD PLUGIN: EconomyPShop v2.0.2

Code:
[168] 				$now = microtime(true);
[169] 				if(!isset($this->tap[$player->getName()]) or $now - $this->tap[$player->getName()][1] >= 1.5  or $this->tap[$player->getName()][0] !== $loc){
[170] 					$this->tap[$player->getName()] = [$loc, $now];
[171] 					$player->sendMessage($this->getMessage("tap-again", [$shop["itemName"], $shop["price"], $shop["amount"]]));
[172] 					return;
[173] 				}else{
[174] 					unset($this->tap[$player->getName()]);
[175] 				}
[176] 
[177] 				if(($cloud = $this->itemcloud->getCloudForPlayer($shop["owner"])) instanceof \onebone\itemcloud\ItemCloud){
[178] 					if($shop["amount"] > $cloud->getCount($shop["item"], $shop["meta"])){
[179] 						$player->sendMessage($this->getMessage("no-stock"));
[180] 					}else{
[181] 						if($player->getInventory()->canAddItem(($item = new Item($shop["item"], $shop["meta"], $shop["amount"]))) === false){
[182] 							$player->sendMessage($this->getMessage("no-space"));
[183] 						}else{
[184] 							$api = \onebone\economyapi\EconomyAPI::getInstance();
[185] 							if($api->myMoney($player) > $shop["price"]){
[186] 								$player->getInventory()->addItem($item);
[187] 								$api->reduceMoney($player, $shop["price"], true, "EconomyPShop");

Backtrace:
#0 (): pocketmine\Server->crashDump(boolean)

ImagicalMine version: 1.0dev #0 [Protocol 43; API 1.14.0]
Git commit: 0000000000000000000000000000000000000000
uname -a: Linux localhost 3.4.67 #1 SMP PREEMPT Sun Oct 5 10:12:48 KST 2014 armv7l
PHP Version: 5.6.2
Zend version: 2.6.0
OS : Linux, android

Loaded plugins:
AdvancedKits 4.0.1 by luca28pet for API(s) 1.12.0
VoteReward 3.0.2 by LDX for API(s) 1.12.0, 2.0.0
EconomyAPI 2.0.9 by onebone for API(s) 1.0.0, 1.1.0, 1.2.0, 1.2.1, 1.3.0, 1.3.1, 1.4.0, 1.4.1
EconomyAuction 2.0.2 by onebone for API(s) 1.0.0, 1.1.0, 1.2.0, 1.2.1, 1.3.0, 1.3.1, 1.4.0, 1.4.1
EconomyCasino 2.0.2 by onebone for API(s) 1.0.0, 1.1.0, 1.2.0, 1.2.1, 1.3.0, 1.3.1, 1.4.0, 1.4.1
EconomyJob 2.0.4 by onebone for API(s) 1.0.0, 1.1.0, 1.2.0, 1.2.1, 1.3.0, 1.3.1, 1.4.0, 1.4.1
EconomyLand 2.0.9 by onebone for API(s) 1.12.0
EconomyProperty 2.0.6 by onebone for API(s) 1.12.0
EconomyPShop 2.0.2 by onebone for API(s) 1.12.0
EconomySell 2.0.7 by onebone for API(s) 1.12.0
EconomyShop 2.0.7 by onebone for API(s) 1.12.0
iProtector 3.1a by LDX for API(s) 1.9.0
ItemCasePE 1.0.8 by aliuly for API(s) 1.10.0, 1.13.0
ManyWorlds 2.0.3 by aliuly for API(s) 1.10.0
SimpleAuth 1.7.1 by PocketMine Team, shoghicp for API(s) 1.12.0
EconomyTax 2.0.3 by onebone for API(s) 1.0.0, 1.1.0, 1.2.0, 1.2.1, 1.3.0, 1.3.1, 1.4.0, 1.4.1
TimeCommander 2 by LDX for API(s) 1.0.0, 1.1.0, 1.2.0, 1.3.0, 1.4.0
BanItem 2.1 by LDX for API(s) 1.0.0
ItemCloud 1.3 by onebone for API(s) 1.4.0
WorldEditArt 1.0.0_beta_dev_#048 by PEMapModder for API(s) 1.0.0
ItemEffects 2.5.0 by XFuryMCPE for API(s) 1.12.0
SignStatus 3.0.0 by xpyctum for API(s) 1.0.0
EssentialsPE 1.1.3 by LegendsOfMCPE Team for API(s) 1.12.0
SimpleAuthHelper 2.0.4 by aliuly for API(s) 1.12.0
PurePerms 1.2.2 by 64FF00 for API(s) 1.12.0
TapToDo 2.2.1 by Falk for API(s) 1.0.0
TimerBan 2.1 by onebone for API(s) 1.2.0, 1.2.1
ClearLagg 1.1.0 by LegendOfMCPE for API(s) 1.0.0
FactionsPro 1.3.2 by Tethered_ for API(s) 1.12.0
EconomyUsury 1.0.1 by onebone for API(s) 1.12.0
EconomyAirport 2.0.4 by onebone for API(s) 1.12.0
PureChat 1.3.3 by 64FF00 for API(s) 1.11.0

----------------------REPORT THE DATA BELOW THIS LINE-----------------------

===BEGIN CRASH DUMP===
eNrVXAtz2ziS/itYJVVjX4l6y7I1q9z5HPs2t/ZYZzuXrYtSLogEJY5JgkOAljVT89+vuwG+JE0s
J76a23lUyCbQ6K/fAKn81tBBJBrj7mA4OBn0T3pHzYZIU5k2xr819DqBR43z+/Obm+ubRrMRCaX4
AmlnPAyZloyzSERzkTI/i10dyJgthD4LZeZdyHQa8rVIDw4ZkOMsDIGDH4Q4vX3uylhG6+ntUib3
j71Wp9VrJUuetlXqtmUs5vB/W5hBiYJBtRnAKAxiFHs0+r3ZSMJsEcQoaX2MKz2BOLpHx/Bwps2/
b2O5YhMWBW4qEfyBTjNx+COM7x6dVMYF/sFfAqWEPnirl4Fy3mmefH6bECbnHcD8icPkwy8AL2XE
1GFfH/m5+4W9m7Bua8hoztcHd76wv0wm7G0o3cPfULpRpyId4PjqdED4Gac2SbQvBG/UrTPIZykR
e1fGtDlWYJRTZg1YwuELHsSzRhO4ojk+zxqBFhEuNmt8gUUsMUkDt07hkcxiDaQvh0bJo15NilTo
LI3Nk37lye8iVMLgHtQmZPEeNjH8hlV+RDkCCl2M6pY+eOui04LWLGNERyRiu+HROTa5ikUK0A4P
WRArzWNXSJ/NZtaBZ7OCy2z2AS6JjTXmcQ0UiLClMPaOva2IgNSDqvJrao6E5iSJ4X5S4/4CW8fS
UVq6D7OGNddx3etKsxx3N9ZADBVTfIgfRaxluj44dN65PD71PNQBqBqFB03HYsWI8hyoHc50CCqf
QHT4HMQxmI97G/K8EHXC0XNz1P0NZhXcg+11eBIAoIrhbeoC+mxms9Lp9MN4THoxnnJgVxpusUNF
wkznXbS+Am7rXK2H6BEbgWaxH20xqaDfNAa3liBDWClGuxiQEKnwMlfUBNkV75hFm2xWy8Ggzh8b
kKB1CrptjD833nTYweGYJeBgQkcBaupWpI8opJtytXyfRcnBXMpQ8PgQuDYWAiKMh5jFYZSCAgNy
dlsdTzyC2PMsCL3GuAMlAHK5dCUMHPSbDZCbhnUHrQ4MWwQabjt7/gMTUv4QBnOc0xoRhyzmWCUb
l0GcPTFIqzxcSqVZvzVoHY3Ymy67vZqy6c35+dX0jt1mMbt2NRuybmfc7Y0Hx+zvt3es1+kOGE+j
xxFWwmSZAMNh66jVg7tfwUHhtge3HfPwXqp8QSDQDY+9VAZeoyh5CvVy6j2iO3l/DzTdW1Fr5GZF
e6CTVhcoPNNLmSo0S5i5vHecCI0qJ+V9Ru1BWUaCiPk8FCAembjhiQSExXnwTElfv68SIk6VuLr6
bHaFRKjZkiPI6fXt3afrm8v3QFqJuQIvBOpS60SN220w1jKbt1wZtQux2jUwAP+/pRY3YsVTr4K4
Qqzi7WNzUcd7+f4f20ibDWxDvhkx8JzNShH2Bw2YH2FaStNakZuIFsABkGXeqICsEKsgUfSTOkib
i2pAO4QTANs/e8WfXfqzb+/79n5g7wdw/416eSYlPqMhbBsrqsiox9yhDvtgUyW9P08lVUu9RD0G
SamiAtn+ajrjKojltpYs/Z9fSS4BKXRU4NpfRf8p59v6QeKmcgb/FEH1s5wX2jAo9lfFJY+9bV0Q
9RsyzLNF4xtNHoI8BUQr3P4Yp6lMRKrX2ziLJ5tYj14Rq5X325AnVsICfUXkF2iA9sTb8O1W+cUZ
4Xuagy2E2EyW8PId/t7YbkUYbkMj6iay0Z/nwQrkKUBa4V6Acaf5dlrvz8RYNeT+dgzApbVwtTl2
shArxHo71+Vf7+ZOvrOJKxf+5s4V+DhXZ9PzdgUE4KQzAK7E9LyCs0Js1jc5reM6UB4GWbiuG7Io
Pv1vR2342tMKkCQRewG3xrvi8fqTTEOvuvuoEDfds78fqO/EEoEAKxLgJVhugygJxSlIV8FSIdYN
NNrcR01pX3sF+1p2J3gEDyEgFsvATV4td5bCwNa5KphFd3t3enP3cfqcg5aStitcynRzx5+2sw0S
n7HmP0HzqPlTkaIMoj0c4y6IxJmMwKs8UU1SdXpFOb2vpqg/Ukm/gP59Kawm1ksC4N95jPmogjCn
1A3fbTyL73vkt4u+RPLifHUztRKtHrh7OO3gFdqbyukv4jgLuVJ7nghYHq1ItO1RT/tfzcWk4Irh
Sjn23Av0aaorwGvkzarSuZ8Lze898Xj/pjPYqDHT8yueXEkP3fmVLJqIiCcRsZzNKCcLkIynejbb
kPOlZbYibPs24mHo/M+ZM7X60qkQ7YgrDQ9r61hnOfd9KMxqw11yat3dhxSXFTX94yJL11jhXy2x
P/nAEXxmv9rbUC2uHZ+7rVgQottgEd9qrjNVq1wFcfNEbAPPU7J2dRa9lsnLhbFKVYTYp+FVSsQ6
4KGqtUk1ct2ltwL6UixQpGsfLWRK8WuZqSrGbHYJcCjvv7hBJAmNgO0atFoX8jcRJrV6s/XomfOK
Xd3Vs71/pSPYo9NakiDf3CrzUPxMB9vArl2+GHCSHWG8hR6UNc1SMRVpVPX7klZ3lN7mzvZocHHR
6byac9wbfrNZIUDl8uU9Gs60Wii5YDPCkzv5vnrAl1Pq3rBVpi94+PBaIa55oqUnodco1t6zj0qh
um+0UET6aoexq0ZXG8nvrdX4JUA657Hpnaw8ewA6CwVPL/liUUFU0jbzVGdXnjJZ4LXsUiz+Wtmp
RANwLzgdRyvY1lYAV6kbndZmxN0JvRSp8O5fLegqi89m9mb/ttFuBD4qqL7bOx5D3mygun/eAUum
qEvYEO8Fb1CCNJG1VnHjwTecf/9fYeVGpPJVSCHiHngxYZ4tud6oCkTadNH+80Wh+xzEMkFvIayF
xx8UC5SrvPruUkFMfsf3xDwF8FA78yCit+0te6YcCHyt/GZa3LEzGfvBguFnWrN0Fr+5kjG7EHN2
zLrDcac77h+zj3dn+Cr7CJ8bdg4qeHIjoJT/ys9S7uvKMzTZpNvrD4ZIXMBI2AqISQfvIv7kmC8K
1GTYIZJK+Cp2EnNqBkqbOF0kr5aAPQyUnkjfR4KxhPNLJtL1RMYVUgreYimeUG4aJMTHfGfAIkiJ
LFNBvGDlGYhzNSVxpPYms6zT4aMT80doQZk7n7AxxsytePfOXAxuhHer0XUN/a9/reDHj+gmsUxh
e0JrAPx07YRBFIBaOp3OFVJhZ6idLPG4FjlAHscyi11hFeRwdxmIRxFBp6gsvMdArBwvMJ+TTIxF
YBMkV44fBotloSujUx4HIEM+19AiOc8JS556rkyL9ZPHJNdi4PuBm4V6PemRDembDC1TRwmtQZNq
QhhAutC4Am3ySpoSwgM79obHo5JIenl/fnH68fIOqWi2VgI7ZJjsTf6F/gE4mZaO4o/CykJ+4JAj
kF/4MgUVFV5lZYf6otAejstDEJyTA+RgFHlJKBfo5PkM/Oai6D1b6yjEuGBYRphLIZGlxIUig8Gq
7EPEFwHwR/+BQGF3S6EEyzXCeCoYVDoGUii44Jq5aFHN5oIFsRtmsAmGC7YVkMjrVkYw00cGmzwV
90WTSSyiClmyeSr4A1vLLLW8WOAzUEbgB7QC2DSFUIJOHRj/JFYFu7YnfA5WVWwl4x8040kChZ6h
xiPACtDCNX65iZ9LGdirpYhZlixS7gGD1ixGJzfMxrOYvblbQq/uhEACKUIeLzK+EAy/wiSN2YBQ
AdzTJzTBr6RTnHq2FK5FUZ8IAuT5TsStVfAQJMILeEumizbetS/BF+6lf//h9vr+qH/i9O5xHqix
YDRmM0jci1kDF/q0pAYEv13Fj8IYfseqdEr61SmPFXgL6I0ekzZJUoHfawIwMqknHgNXsCXsWkIy
cgSMjSOWS9KHaUBXy0x7EkPNfGyGwlwnqsmuGWakwAPGF8JdyszId4rxy9DBMUXZTRB7DDj7L0x1
MIRSXr49GtN3VzjxdgnzOHqrkiCWXc7YjFtGkPjAG6FqgUcQTKjIMBIqn4cKKx84gHwulSjZn1Ny
zfkAdIbJgoHfgmugqPM1sw4Fw20qLp6W+njzKQCNyxh8i3seS4UyLohigtM9gDgcuhrKcwwcby5Q
H6Ak8UvG6ZPjRfAIYx95mAl2YJeEgnQIzM16UAIEVh0HzLpYiHQMT3HlnzL6Uhni6lStY/eOqwdw
/fQBIqmFzz8q0Ag6ag4SRy1T6D0y8A0YDVajzMZsBgTfbYIaItCawnaC1AJ1GmlRFkMI4RDifUu+
A3ggylL5BJkYytka4ZDPx4VoqFUjzgcfQ5U+soaQbLJA/4DfXKc0yxNYH8kdN+ayA0AAdmY91Ahh
cCzKMXHCsDVViIL2P0I5B8Viy8IMmVFxwuQUiQWfrzUIxG6NKB1a3ORQE/KAaRWQYKRshuXHFjlL
UqQXPwB3gXwl8ENE5OJDsshXNOZfYmVGp11IwCEx+lBnsM6ChDRVc8w6M8oZlJ015Bzu/T8XHzu+
rwiPpfe7hIdil9D6NmcV8lhuikFIYW0VXi4NrpmL1O30BkYq6GADSXUJY1Hhgi5lZitdEW9dWApS
jYc+RiMciAdhIo3yuYwhgUGEgt4wO/yRWo06oaqHlOox1s2wGRVe5AHRV0aySUe4wjWmECx1NLy1
PRhh234dVJgIFyuiIrWgrEbHZm4BADQpElXC7HcsTnW4UyCLum9QL3g6B/s7rgxD071ihO3UKrkT
imLnMDtHYocaZ1R7q1JAW5KBLxw285yw4QzWG0xepSNs4h6VXtZi16bw0R14BJSc0CsECSCDrGJW
io5+yxKSHAAeQadKGNmbC4qErdxIvmJmF6D8VEZ5isW59rlTzUoVmwIIa7pNV9jhP5V5uI1wl1n8
oIy+L8nrMSESESXD7RSiYfkHzBieKXQiygxysBnApqbkhaxyM9tAOTmycr6XZtqm+bAIYMtkplU5
mFXssFfATIUI+lvwXYM6b2ztQvigqN5fZTWLY6HRFkUPB64Rmko45xq2HdiIcGyOoQCCP9msRAFo
OlT71CSjuShqIqWbN9X0lT/BwE/XGnk3mdOtODPWPlrW0bkokFaGRyarlLWWdhFY6DyT7qwBzVwg
Wpla7G+wFQL1TqApBsc9m35swlyQYA75ZxV4emmyNsV3wd4h9mM2so1B2TIoUkxlaIudehBPSx76
+NrOdDGeAD+zC8GSxv9kXA3IojpXeFX6pPMnDD5sg3jYNIGNC38KYmgnARa4jSDXxlr/cRpP806h
bN6xCcJJ9D0ydu5x4tjbak+G++R5thjbpuMd62KzYSsLdpX0OO8oFeWxpcg7zZk1BZSRsk9UrK3o
lU+TtReuUS2+jFaVRfO9YW0DIfImEuUGJGbrREOteyFcMrgLStTkYXaKY6aMWQSPFnZjAYDMLxNA
XHA5cFJKSrzGHzInbs10ZXlQpt6WhmKUTPfmp+u78zGjrAv/uRnssmLYZREjek2BpiPx7MqFeIWJ
T2vWcmFDAZnEYiUvopIEkqDXaPScXseWEExlpjKhG+EmGem2HNmor5PzHGZ64VsMVwQ450pUFjvo
QqDsWKXJevCgu+uB0G7rkIJWiaoU5A53yBn3WPaYhwlITGY9LP3GkrSbLbe5mAhoF4TdE6YDHq74
Whnelk9Fi+xOLha0BVGrQCN3aes+bhtsVoG2nOMq1FkzcApou8Gf1NKoN6atkhmCRq5upzFtNKnv
/jcwlptiXkl/UMUuQbMdB3LlyPYnw/aKFknLzZFdrkzEtUJE8XBKP3eqVDJlm89cm2gHVAvuffCs
CS7HbPDHU3kKVM8YwfCol0/WPentnE1hEguzM54Lw20ufEypdJSE+kd/KriaA6ZKDjcp/JY/QveA
ug3wAEDgPjJZ28MOW1SLzowynk/v/vL8bvOxn4U0TCqIOQdzTeCamkh7yRRPGMDDgW2uqp+lMRa1
yTxCp48o6WOlLPAX2ckYAxWaG+OKPzG+qRfYzLlU6ErHrtuCou2Ge0GmKtOsHbiVjrKNmWoDCMdD
24XJFU/y7Nlgxe1dfCtjQgIPCza9qNyh5rK3toW3iXzFAzps+CUTmbD2tfMpfxHdUWCsMTv+Jm6J
TLLQcrPXWGM3GM9iSi4OaA+FNueVDvmRQk2iKiMoOhoPkSy1a/McHhGOmelSc5Pij8iyBLo207oa
h6QsaDomywu4jHCWXRCZDvF2xXGhgkg0Hs0D8HwzxJ5OmsOGscmqeC6CP2RjhmqaBeskxnvtlqTI
0ujXDh5Z1SlFXaxRk2USxL4s3QB/hTY2S7YqB5jQ0ZF8sYzXEe5XKEIU6FcVguIGzD5m5WMSGHyN
M75YQBm1pxzF+REmSvw538NuNEYeZKd2yRMGUCSMCOdPHKukucE2A5zHvpYZM3tBj8CyuL8ds894
6UBpaNKG9ws1EdIEJ6ue62GKKU7vFgw1hpUXu0bTZz6wA9u9tGDAYasAUoYR+PTC+OGeBcZM2MUq
78znISikSCns8xD6rNHJF1rizB4yY28TwBI0ttikUXMC80z1sukP0Ciskgap2U6XbTTDI8pIhJo6
bNrlzbOU0jQeRzJqvRUVb5TRpM68CaseOlPTle+WzJY1P/+nveiuM2yShWq4on4JV42gjQrA4LbB
qbgArUoCGHXj6wKMd6pj5WpjdnF5ejfu/ThqDk+eus3+U7/Z+7H7owd9iEl1B/itiItpaXLcYQsI
CmXuBsNDOuIP7Jl9echPcdRsiCctYvQ4+orkDKpa5beZmHkrt1BcFsXExMWh9kb9EgZa9M3vRh3z
E9VfzQ9JzacKcxfccFmMx4Pl2ONpSTB/40J+l6WlhH4QavwSCFh3zXcEvk6Kp4uovF5CLjAvqmHQ
z6r49AXfWkdzc9ZdDIZWeZ3oEoHmKJBXgXs7vaRV8TpxocUt564BMP1s1V6xIb4c7yJy5uA7wl5n
2OnjX4vwAQzq90d9wYeeNxz2j0dH3UHniB93ej0+mB/z/mgw6B7Pe4OOYG9hpekS1VL8GCWRKngq
lW7PMOyALgK9Eb7dgAOV1jsWQ9/l0MAPYNmOPxq5o+Pjo+EQlu6f9Pqi35mfjE48j9ZTy0iWKlSU
uVQdaWCUD4O1fBAxVK20oECP95AK3yiqNQTKmtM7JPzoAwf8GiTmrtcaNH7//X8BPEC1wA==
===END CRASH DUMP===

I Have Plugin Item Could Installed

**Comment by PainTR** [comment]
I have item cloud too

**Comment by blah123454321** [comment]
Maybe it's not compatable with ImagicalMine

**Comment by BUTTER-JP** [comment]
Me too.It has occurred in recent.
ClearSky Crash Dump Sun Feb 28 17:49:13 CST 2016

Error: Call to a member function getCloudForPlayer() on null
File: /plugins/EconomyPShop_v2.0.2.phar/src/onebone/economypshop/EconomyPShop
Line: 177
Type: E_ERROR

THIS CRASH WAS CAUSED BY A PLUGIN
BAD PLUGIN: EconomyPShop v2.0.2

Code:
[168] 				$now = microtime(true);
[169] 				if(!isset($this->tap[$player->getName()]) or $now - $this->tap[$player->getName()][1] >= 1.5  or $this->tap[$player->getName()][0] !== $loc){
[170] 					$this->tap[$player->getName()] = [$loc, $now];
[171] 					$player->sendMessage($this->getMessage("tap-again", [$shop["itemName"], $shop["price"], $shop["amount"]]));
[172] 					return;
[173] 				}else{
[174] 					unset($this->tap[$player->getName()]);
[175] 				}
[176] 
[177] 				if(($cloud = $this->itemcloud->getCloudForPlayer($shop["owner"])) instanceof \onebone\itemcloud\ItemCloud){
[178] 					if($shop["amount"] > $cloud->getCount($shop["item"], $shop["meta"])){
[179] 						$player->sendMessage($this->getMessage("no-stock"));
[180] 					}else{
[181] 						if($player->getInventory()->canAddItem(($item = new Item($shop["item"], $shop["meta"], $shop["amount"]))) === false){
[182] 							$player->sendMessage($this->getMessage("no-space"));
[183] 						}else{
[184] 							$api = \onebone\economyapi\EconomyAPI::getInstance();
[185] 							if($api->myMoney($player) > $shop["price"]){
[186] 								$player->getInventory()->addItem($item);
[187] 								$api->reduceMoney($player, $shop["price"], true, "EconomyPShop");

Backtrace:
#0 (): pocketmine\Server->crashDump(boolean)

ClearSky version: 1.1 #CuttingEdge [Protocol 42; API 1.13.1]
uname -a: Linux 133-130-109-170 3.10.0-327.3.1.el7.x86_64 #1 SMP Wed Dec 9 14:09:15 UTC 2015 x86_64
PHP Version: 5.6.2
Zend version: 2.6.0
OS : Linux, linux

Loaded plugins:
AdminSystem 1 by BUTTER for API(s) 1.13.1
BanItem 2.1 by LDX for API(s) 1.0.0
ByeSteve 1.0.0 by mfmfneko for API(s) 1.0.0
IDCheck 1 by tukikage7127, tukikage7127 for API(s) 1.12.0
JoinQuitPopup 1.2 by  for API(s) 1.3.0
LoginSystem 4.2.7 by tukikage7127 for API(s) 1.13.0
MSpawns 1.5 by EvolSoft for API(s) 1.11.0
Message 1.0.0 by  for API(s) 1.11.0
PocketGuard 2.1.1 by MinecrafterJPN for API(s) 1.10.0
RealTime 2.1 by Guillaume351 for API(s) 1.0.0
SignConsole 2.0.5 by Hmy2001 for API(s) 1.6.0
SignPortal 1.1.2 by 99leonchang for API(s) 1.3.1
TimeCommander 2 by LDX for API(s) 1.0.0, 1.1.0, 1.2.0, 1.3.0, 1.4.0
VoteReward 3 by LDX for API(s) 1.12.0, 2.0.0
WEdit 2.3.0 by Gonbe34, Gonbe34 for API(s) 1.0.0
WorldProtect 2.2.0 by aliuly for API(s) 1.10.0, 1.12.0
iProtector 3.1a by LDX for API(s) 1.9.0
EconomyAPI 2.0.9 by onebone for API(s) 1.0.0, 1.1.0, 1.2.0, 1.2.1, 1.3.0, 1.3.1, 1.4.0, 1.4.1
EconomyAirport 2.0.4 by onebone for API(s) 1.12.0
EconomyJob 2.0.4 by onebone for API(s) 1.0.0, 1.1.0, 1.2.0, 1.2.1, 1.3.0, 1.3.1, 1.4.0, 1.4.1
EconomyLand 2.0.9 by onebone for API(s) 1.12.0
EconomyPShop 2.0.2 by onebone for API(s) 1.12.0
EconomySell 2.0.7 by onebone for API(s) 1.12.0
ItemCloud 1.3 by onebone for API(s) 1.4.0

**Comment by Infernus101** [comment]
How to ban pshop sign in other worlds?

**Comment by onebone** [comment]
I cannot reproduce this error.

**Comment by Infernus101** [comment]
Onebone, itemcloud and pshop arent working together, it says 'ShopOwner doesnt own an itemcloud account' even if he does, i have tried it myself, i am using genisys
