### ISSUE TITLE
GPLv3  위반자 발견 - 금전적 이익

### ISSUE THREAD

**Issue by ParkChanSol** [onebone/EconomyS#344]
신고 링크 : http://blog.naver.com/sdt1027/220875622771

증거자료(pdf, 이미지)
![naver_com_20161204_230458](https://cloud.githubusercontent.com/assets/20399222/20866703/83a978c8-ba76-11e6-9256-04972fa62b8a.png)
[Pictures.zip](https://github.com/onebone/EconomyS/files/629563/Pictures.zip)
위에껀 사진, 밑에껀 pdf 로 모은겁니다

**Comment by ParkChanSol** [comment]
@onebone 긴급사항

**Comment by onebone** [comment]
https://www.gnu.org/licenses/gpl-faq.ko.html#DoesTheGPLAllowMoney

GPL 은 프로그램을 상업적으로 이용하는 것을 허용합니다.

**Comment by ParkChanSol** [comment]
@onebone 그럼 직접적인 판매도 허가하는것인가요?

**Comment by onebone** [comment]
https://www.gnu.org/philosophy/selling.html

Since free software is not a matter of price, a low price doesn't make the software free, or even closer to free. So if you are redistributing copies of free software, you might as well charge a substantial fee and make some money. Redistributing free software is a good and legitimate activity; if you do it, you might as well make a profit from it.


> you might as well charge a substantial fee and **make** some money.

위를 보시면 아실 수 있다시피 GPL 은 소프트웨어를 판매하는 것을 허용하고 있습니다.
